-- ============================================================
-- حصاد أسئلة الـAgent — خِدْمَتي AI (30/9/2026)
-- نفّذ الملف ده مرة واحدة في: Supabase Dashboard → SQL Editor → New query → Run
-- الجدول بيستقبل أي سؤال الـAgent عجزت قاعدة المعرفة المتحققة تجاوبه
-- → ده بايبلاين المحتوى الجاي: قائمة مواضيع مقالات مدفوعة بأسئلة مستخدمين حقيقية
-- الـWorker بيكتب فيه بـ SUPABASE_SECRET (service_role) — يتجاهل RLS من غير سياسات
-- ============================================================

create table if not exists agent_questions (
  id           bigint generated by default as identity primary key,
  question     text not null,
  matched_slug text,
  source       text default 'site_chat',
  created_at   timestamptz default now(),
  handled      boolean default false
);

comment on table agent_questions is 'أسئلة المستخدمين اللي قاعدة المعرفة المتحققة عجزت تجاوبها — بايبلاين المحتوى';
comment on column agent_questions.handled is 'بقى true لما نحوّل السؤال لمقالة/صفحة متحققة جديدة';

-- فهرس عشان تصفية الأسئلة الجديدة
create index if not exists agent_questions_unhandled_idx on agent_questions (handled, created_at desc);
